### ISSUE TITLE
From a plugin, a TypeError is thrown when trying to create a document when omiting the original request

### ISSUE THREAD

**Issue by lethak** [kuzzleio/kuzzle#1213]
## Error
```text
TypeError: Cannot read property '_id' of null
at kuzzle.indexCache.exists.then.exists (/var/app/lib/services/elasticsearch.js:285:39)
at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/var/app/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/var/app/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/var/app/node_modules/bluebird/js/release/promise.js:693:18)
at Async._drainQueue (/var/app/node_modules/bluebird/js/release/async.js:133:16)
at Async._drainQueues (/var/app/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/var/app/node_modules/bluebird/js/release/async.js:17:14)
at Immediate.args.(anonymous function) (/opt/node-v6.13.1-linux-x64/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:133:29)
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5)
```

## Not Working

```javascript
        const createDocument = context.get().constructors.Request({
            "controller": "document",
            "action": "create",
            "index": 'foo',
            "collection": 'bar',
            "body": {foobar: 1}
        });

        return context.get().accessors.execute(createDocument)
            .then(response => {
              console.log('OK THEN')
            })
            .catch(error => {
                console.error(error); // triggered "TypeError: Cannot read property '_id' of null"
            });
```

## Working
(please note the presence of `originalRequest`)
```javascript
        const createDocument = context.get().constructors.Request(originalRequest, {
            "controller": "document",
            "action": "create",
            "index": 'foo',
            "collection": 'bar',
            "body": {foobar: 1}
        });

        return context.get().accessors.execute(createDocument)
            .then(response => {
              console.log('OK THEN') // triggered !
            })
            .catch(error => {
                console.error(error);
            });
```

## Expected
An anonymous request should probably be used internally when omitted in the parameters

**Comment by Aschen** [comment]
Hi @lethak ,

Please can you tell me what version of Kuzzle are you using ?
I suspect that your are using a version prior to 1.5.0 in which this bug has been fixed.

If you can not upgrade your Kuzzle version, you can use this workaround in the meantime:
```js
createDocument.context.user = { user: 'admin' };
```

Tell me if this solve your problem.

**Comment by lethak** [comment]
I was using 1.4x, closing, thanks.
