### ISSUE TITLE
Bulk import: Kuzzle won't do anything if the payload exceed maxRequestSize

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle#1221]
I have a csv that contains approximately 10K rows, each row will be a document in ElasticSearch. 
When I try to do a flat bulk import without changing any configuration inside kuzzle, the endpoint doesn't respond at all, resulting in data not imported nor errors triggered by Kuzzle. 

I had to create a .kuzzlerc and override the `server.maxRequestSize` and set it to 10Mb to be able to do my flat import. 

## Expected Behavior

Import the data if possible OR trigger an error saying the payload exceed the maxRequestSize

## Current Behavior

Kuzzle remains silent if the bulk payload is too big and won't trigger an error.

## Possible Solution

Check the payload size before process the request

## Steps to Reproduce

1. My `jobs.csv` is there : https://gist.github.com/Tyki/0eb2e0165946f6531e1b9624da3da771
2. Here is the script https://gist.github.com/Tyki/3ef61a666a6b9c221a6a28fa015e6852
3.
4.

## Context (Environment)

Last kuzzle : 1.5.3

**Comment by scottinet** [comment]
Hi,

It looks like a problem in our websocket driver. I think your request simply got discarded silently.

I'll try to make things better: your socket must be closed unexpectedly with some kind of socket error code. 
Do not expect a proper Kuzzle error on that one: for obvious security reasons, the maximum size of a message is handled at protocol level, before messages are handed over to Kuzzle.

**Comment by scottinet** [comment]
After investigation: our websocket driver runs fine. And, in fact, everything run fine: 
* your socket gets forcibly closed by Kuzzle because your message exceeds the size limit
* by default, the Javascript SDK does not show network errors, such as unexpected disconnection, and reconnects automatically

This becomes apparent if you add listeners to [SDK events](https://docs.kuzzle.io/sdk-reference/essentials/events/):

```js
kuzzle.on('networkError', err => console.error('network error: ', err));
kuzzle.on('reconnected', err => console.error('==> reconnected'));
```

When executing your code with these listeners in place, you obtain the following output:

```
network error:  { Error: Unable to connect to kuzzle proxy server at "127.0.0.1:7512"
    at WSNode.<anonymous> (/home/scottinet/tmp/sandbox/node_modules/kuzzle-sdk/src/Kuzzle.js:367:27)
    at WSNode.emit (events.js:182:13)
    at onClientNetworkError (/home/scottinet/tmp/sandbox/node_modules/kuzzle-sdk/src/networkWrapper/wrappers/websocket.js:172:6)
    at WebSocket.client.onclose (/home/scottinet/tmp/sandbox/node_modules/kuzzle-sdk/src/networkWrapper/wrappers/websocket.js:72:9)
    at WebSocket.onClose (/home/scottinet/tmp/sandbox/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:182:13)
    at WebSocket.emitClose (/home/scottinet/tmp/sandbox/node_modules/ws/lib/websocket.js:172:10)
    at Socket.socketOnClose (/home/scottinet/tmp/sandbox/node_modules/ws/lib/websocket.js:780:15)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close (net.js:606:12)
  internal:
   { Error
       at WebSocket.client.onclose (/home/scottinet/tmp/sandbox/node_modules/kuzzle-sdk/src/networkWrapper/wrappers/websocket.js:69:17)
       at WebSocket.onClose (/home/scottinet/tmp/sandbox/node_modules/ws/lib/event-target.js:124:16)
       at WebSocket.emit (events.js:182:13)
       at WebSocket.emitClose (/home/scottinet/tmp/sandbox/node_modules/ws/lib/websocket.js:172:10)
       at Socket.socketOnClose (/home/scottinet/tmp/sandbox/node_modules/ws/lib/websocket.js:780:15)
       at Socket.emit (events.js:182:13)
       at TCP._handle.close (net.js:606:12) status: 1006 } }
==> reconnected
```

**Comment by cklinx** [comment]
any news about it? Same problem. I cannot import big file but only small one.

**Comment by scottinet** [comment]
Hi,

There is no issue, everything work as expected: to prevent DDOS we enforce a requests size limit.

The default is set to 1MB, but you can change it by [creating a new Kuzzle configuration file](https://docs.kuzzle.io/guide/1/essentials/configuration/) and set the `server.maxRequestSize` property to a value more suited to your needs.
