### ISSUE TITLE
How import big json data? Error: Network Error: { Error: Unable to connect to kuzzle server at

### ISSUE THREAD

**Issue by cklinx** [kuzzleio/kuzzle#1280]
Any way to import 1Gb json with bulk or kuzzle.document.createOrReplace?
I get always this error: 

```
Error: Network Error:
`Network Error: { Error: Unable to connect to kuzzle server at yourIP:7512
    at WSNode.clientNetworkError (/home/user/Documents/kuzzle/node_modules/kuzzle-sdk/src/protocols/abstract/realtime.js:57:29)
    at WebSocket.client.onclose (/home/user/Documents/kuzzle/node_modules/kuzzle-sdk/src/protocols/websocket.js:84:16)
    at WebSocket.onClose (/home/user/Documents/kuzzle/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:189:13)
    at WebSocket.emitClose (/home/user/Documents/kuzzle/node_modules/ws/lib/websocket.js:191:10)
    at Socket.socketOnClose (/home/user/Documents/kuzzle/node_modules/ws/lib/websocket.js:850:15)
    at Socket.emit (events.js:189:13)
    at TCP._handle.close (net.js:597:12)
  internal:
   { Error
       at WebSocket.client.onclose (/home/user/Documents/kuzzle/node_modules/kuzzle-sdk/src/protocols/websocket.js:81:25)
       at WebSocket.onClose (/home/user/Documents/kuzzle/node_modules/ws/lib/event-target.js:124:16)
       at WebSocket.emit (events.js:189:13)
       at WebSocket.emitClose (/home/user/Documents/kuzzle/node_modules/ws/lib/websocket.js:191:10)
       at Socket.socketOnClose (/home/user/Documents/kuzzle/node_modules/ws/lib/websocket.js:850:15)
       at Socket.emit (events.js:189:13)
       at TCP._handle.close (net.js:597:12) status: 1006 } }
```
Small files work fine.

Thanks in advance.

**Comment by Aschen** [comment]
Kuzzle has limits on the maximum size for a request and the number of documents that can be written simultaneously.  
You have to either push these limits or split your big file into smaller pieces.  
We have an example of that kind of import here: https://github.com/kuzzleio/kuzzle-how-to/tree/master/massive-data-import
