### ISSUE TITLE
create collection with mappings and updateMapping problems

### ISSUE THREAD

**Issue by lethak** [kuzzleio/kuzzle#1303]
Using kuzzleio/kuzzle:1.4.3

# How to reproduce:

Within a kuzzle plugin, execute:

```javascript
// Create an index 'sampleindex'
plugin.context.accessors.execute(new plugin.context.constructors.Request({
	'index': 'sampleindex',
	'controller': 'index',
	'action': 'create',
}))
.catch(err => null)
.then(() => {
	// create a new collection 'samplecollection' with some mappings
	plugin.context.accessors.execute(new plugin.context.constructors.Request({
	  'index': 'sampleindex',
	  'collection': 'samplecollection',
	  'controller': 'collection',
	  'action': 'create',
	  'body': {
	    "properties": {
	      "field1": {
	        "type": "text"
	      },
	      "field2": {
	        "type": "keyword"
	      }
	    }
	  },
}))
})
.catch(err => null)
.then(() => {
	// create 'samplecollection2' on the same index as 'samplecollection' but with different mappings, and using same field names as samplecollection
	plugin.context.accessors.execute(new plugin.context.constructors.Request({
	  'index': 'sampleindex',
	  'collection': 'samplecollection2',
	  'controller': 'collection',
	  'action': 'create',
	  'body': {
	    "properties": {
	      "field1": {
	        "type": "keyword"
	      },
	      "field2": {
	        "type": "text"
	      }
	    }
	  },
}))
})
```

the last internal query throws:

```
BadRequestError: mapper [field1] cannot be changed from type [text] to [keyword]
at BadRequestError (/var/app/node_modules/kuzzle-common-objects/lib/errors/badRequestError.js:5:5)
at ESWrapper.formatESError (/var/app/lib/util/esWrapper.js:139:23)
at client.indices.putMapping.catch.error (/var/app/lib/services/elasticsearch.js:605:58)
at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/var/app/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 (/var/app/node_modules/bluebird/js/release/promise.js:614:10)
at Promise._settlePromises (/var/app/node_modules/bluebird/js/release/promise.js:689:18)
at Async._drainQueue (/var/app/node_modules/bluebird/js/release/async.js:133:16)
at Async._drainQueues (/var/app/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/var/app/node_modules/bluebird/js/release/async.js:17:14)
at Immediate.args.(anonymous function) (/opt/node-v6.13.1-linux-x64/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:133:29)
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5)
```

same problem occurs using `updateMappings` instead of creating the collection with mappings

# What was expected

The mappings of samplecollection2 should have been created/updated without this error happening.

Why are the fields of `samplecollection` impacting the updateMapping operation on `samplecollection2` ?

May be related to #1062 but I am not sure

**Comment by alexandrebouthinon** [comment]
Hi @lethak, this is unfortunately a limitation of Elasticsearch. To update a mapping you need to:
- Dump *the index* concerned
- Delete the index
- Recreate the index with the new collection mapping(s).
- Re-import data
For dump and import you can use tools like [elastic-dump](https://github.com/taskrabbit/elasticsearch-dump).

All this can be scripted to manage potential changes in data formats. Internally, we often use scripts in Node.js coupled to the [Javascript SDK](https://github.com/kuzzleio/sdk-javascript)

**If you use elastic-dump:** remember to make the port of the Elasticsearch API (port **9200**) available for the duration of the oprations.

**Comment by scottinet** [comment]
Hi, 

In Elasticsearch, you cannot have the same field name with different mappings within a same index (field mappings are shared across all of an index collections).

**Comment by lethak** [comment]
I was not aware of this, thanks for pointing this out, I found more on the subject here https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html
