### ISSUE TITLE
ERROR uncaughtException when gracefully restarting a docker container from kuzzleio/kuzzle:1.9.2

### ISSUE THREAD

**Issue by lethak** [kuzzleio/kuzzle#1426]
## Expected Behavior
No ERROR when gracefully restarting the docker container

## Current Behavior
The following error happens after issuing the restart command

```text
2019-08-28T19:17:19+00:00 [LOG:INFO] ["Initiating shutdown..."]
2019-08-28T19:17:20+00:00 [LOG:ERROR] ["ERROR: uncaughtException: Cannot read property 'log' of undefined\nTypeError: Cannot read property 'log' of undefined\n    at halt (/var/app/lib/util/shutdown.js:108:10)\n    at pm2.list (/var/app/lib/util/shutdown.js:85:14)\n    at /var/app/node_modules/pm2/lib/API.js:606:19\n    at /var/app/node_modules/pm2-axon-rpc/lib/client.js:45:10\n    at Parser.<anonymous> (/var/app/node_modules/pm2-axon/lib/sockets/req.js:67:8)\n    at emitOne (events.js:116:13)\n    at Parser.emit (events.js:211:7)\n    at Parser._write (/var/app/node_modules/amp/lib/stream.js:91:16)\n    at doWrite (_stream_writable.js:397:12)\n    at writeOrBuffer (_stream_writable.js:383:5)\n    at Parser.Writable.write (_stream_writable.js:290:11)\n    at Socket.ondata (_stream_readable.js:639:20)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at addChunk (_stream_readable.js:263:12)\n    at readableAddChunk (_stream_readable.js:250:11)\n    at Socket.Readable.push (_stream_readable.js:208:10)\n    at Pipe.onread (net.js:597:20)"]
```

## Steps to Reproduce

1. Run a container from docker image kuzzleio/kuzzle:1.9.2
2. Restart the container
```bash
docker-compose restart kuzzle_1
```

## Context (Environment)

Kuzzle version: Docker  `image: kuzzleio/kuzzle:1.9.2`
ElasticSearch Docker: `image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16`

**Comment by Aschen** [comment]
Fixed by https://github.com/kuzzleio/kuzzle/pull/1454
