### ISSUE TITLE
Windows 10 docker Elasticsearch timeout

### ISSUE THREAD

**Issue by ernestasga** [kuzzleio/kuzzle#1796]
Trying to install docker container on Windows 10. 
I tried: 

- Increasing virtual memory to 8gb in windows.
- Disabling Hyper-V

```
C:\Windows\system32>docker run --memory="4g" kuzzleio/kuzzle
[ℹ] Starting Kuzzle 2.4.5 ...
[ℹ] Trying to connect to Elasticsearch...
[X] Cannot start Kuzzle 2.4.5: [FATAL] Service "elasticsearch": initialization timeout
[x] [ERROR] InternalError: [FATAL] Service "elasticsearch": initialization timeout
[...Kuzzle internal calls deleted...]
    at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/var/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/var/app/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/var/app/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/var/app/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/var/app/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/var/app/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/app/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

```

**Comment by scottinet** [comment]
Do you have an Elasticsearch service (or docker image) running?

**Comment by ernestasga** [comment]
I don't.  Should I run Elasticsearch  container first?

**Comment by scottinet** [comment]
Yes. And the redis one too.

There is also a docker-compose file that wraps everything up for you: https://docs.kuzzle.io/core/2/guides/essentials/installing-kuzzle/#docker

**Comment by ernestasga** [comment]
I started elasticsearch container and can access it through port 9200 but I'm still getting the same error.
Also tried these commands to no success
```
1) wsl -d docker-desktop
2) sysctl -w vm.max_map_count=262144
```

**Comment by scottinet** [comment]
your docker images need to be part of the same network, otherwise they won't see each other

**Comment by ernestasga** [comment]
Got it working with `docker-compose up` but can't access from browser 
```
The connection was reset


The connection to the server was reset while the page was loading.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web
```
