### ISSUE TITLE
Elasticsearch Client error: version_conflict_engine_exception

### ISSUE THREAD

**Issue by Stan92** [kuzzleio/kuzzle#1891]
Hi,

I get this warning while launching Kuzzle 
Kuzzle : 2.7.1
OS  : Ubuntu 20.04
Nodejs : 10.19.0

It's not a blocking issue.

```

{
   "message":"Elasticsearch Client error: version_conflict_engine_exception",
   "meta":{
      "body":{
         "error":{
            "root_cause":[
               {
                  "type":"version_conflict_engine_exception",
                  "reason":"[resetTokenSecret]: version conflict, document already exists (current version [1])",
                  "index_uuid":"cbZEEsUwRqir4F2LknIf8Q",
                  "shard":"0",
                  "index":"%plugin-kuzzle-plugin-auth-passport-local.config"
               }
            ],
            "type":"version_conflict_engine_exception",
            "reason":"[resetTokenSecret]: version conflict, document already exists (current version [1])",
            "index_uuid":"cbZEEsUwRqir4F2LknIf8Q",
            "shard":"0",
            "index":"%plugin-kuzzle-plugin-auth-passport-local.config"
         },
         "status":409
      },
      "statusCode":409,
      "headers":{
         "content-type":"application/json; charset=UTF-8",
         "content-length":"535"
      },
      "meta":{
         "context":null,
         "request":{
            "params":{
               "method":"PUT",
               "path":"/%25plugin-kuzzle-plugin-auth-passport-local.config/_doc/resetTokenSecret",
               "body":"{\"secret\":\"...........................\",\"_kuzzle_info\":{\"author\":null,\"createdAt\":1606805548987,\"updatedAt\":null,\"updater\":null}}",
               "querystring":"op_type=create",
               "headers":{
                  "user-agent":"elasticsearch-js/7.10.0 (linux 5.4.0-54-generic-x64; Node.js v12.18.1)",
                  "content-type":"application/json",
                  "content-length":"1126"
               },
               "timeout":30000
            },
            "options":{
               
            },
            "id":51
         },
         "name":"elasticsearch-js",
         "connection":{
            "url":"http://elasticsearch:9200/",
            "id":"http://elasticsearch:9200/",
            "headers":{
               
            },
            "deadCount":0,
            "resurrectTimeout":0,
            "_openRequests":0,
            "status":"alive",
            "roles":{
               "master":true,
               "data":true,
               "ingest":true,
               "ml":false
            }
         },
         "attempts":0,
         "aborted":false
      }
   },
   "stack":"ResponseError: version_conflict_engine_exception\n    at onBody (/var/app/node_modules/@elastic/elasticsearch/lib/Transport.js:311:23)\n    at IncomingMessage.onEnd (/var/app/node_modules/@elastic/elasticsearch/lib/Transport.js:240:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1221:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
```

**Comment by Aschen** [comment]
Hi @Stan92 ,

Thanks for your feedback. We are aware of this error message and it can be safely ignored.

We will fix the auth plugin to remove this error
