### ISSUE TITLE
Problems getting started with launching Kuzzle

### ISSUE THREAD

**Issue by bobeal** [kuzzleio/kuzzle#2247]
## Expected Behavior

I followed https://docs.kuzzle.io/core/2/guides/getting-started/run-kuzzle/ and https://github.com/kuzzleio/kuzzle#run-kuzzle but can't get the `dev:docker` command to start successfully Kuzzle.

## Current Behavior

The command `npm run dev:docker` fails with the following error in both cases:

```
kuzzle_1         | (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 632)
kuzzle_1         | (node:21) UnhandledPromiseRejectionWarning: Error: ENOSPC: System limit for number of file watchers reached, watch '/var/app/node_modules/js-yaml/lib/dumper.js'
kuzzle_1         |     at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
kuzzle_1         |     at Object.watch (fs.js:1582:34)
kuzzle_1         |     at createFsWatchInstance (/var/app/node_modules/chokidar/lib/nodefs-handler.js:119:15)
kuzzle_1         |     at setFsWatchListener (/var/app/node_modules/chokidar/lib/nodefs-handler.js:166:15)
kuzzle_1         |     at NodeFsHandler._watchWithNodeFs (/var/app/node_modules/chokidar/lib/nodefs-handler.js:331:14)
kuzzle_1         |     at NodeFsHandler._handleFile (/var/app/node_modules/chokidar/lib/nodefs-handler.js:395:23)
kuzzle_1         |     at NodeFsHandler._addToNodeFs (/var/app/node_modules/chokidar/lib/nodefs-handler.js:629:21)
```

## Steps to Reproduce

I'm using Debian 10 and just followed the doc indicated above.

Out of curiosity, I tried a manual `npm run dev` and it gave me this:

```
kuzzle@StellioLoad:~/ems-iot$ npm run dev

> ems-iot@1.0.0 dev
> NODE_ENV=development npx ergol app.ts -c ergol.config.json

Debugger listening on ws://0.0.0.0:9229/cb72cef3-cf87-479c-870c-1fe24ae4aec3
For help, see: https://nodejs.org/en/docs/inspector
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/kuzzle/ems-iot/node_modules/es-abstract/2020/HasOwnProperty.js'
    at FSWatcher.<computed> (node:internal/fs/watchers:244:19)
    at Object.watch (node:fs:2249:34)
    at createFsWatchInstance (/home/kuzzle/ems-iot/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/home/kuzzle/ems-iot/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/home/kuzzle/ems-iot/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/home/kuzzle/ems-iot/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/home/kuzzle/ems-iot/node_modules/chokidar/lib/nodefs-handler.js:629:21)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home/kuzzle/ems-iot/node_modules/chokidar/index.js:647:10)
    at NodeFsHandler._addToNodeFs (/home/kuzzle/ems-iot/node_modules/chokidar/lib/nodefs-handler.js:637:18) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/kuzzle/ems-iot/node_modules/es-abstract/2020/HasOwnProperty.js',
  filename: '/home/kuzzle/ems-iot/node_modules/es-abstract/2020/HasOwnProperty.js'
}

Node.js v17.3.0

/home/kuzzle/ems-iot/node_modules/uWebSockets.js/uws.js:24
})();
  ^
Error: This version of µWS is not compatible with your Node.js build:

Error: Cannot find module './uws_linux_x64_102.node'
Require stack:
- /home/kuzzle/ems-iot/node_modules/uWebSockets.js/uws.js
- /home/kuzzle/ems-iot/node_modules/kuzzle/lib/core/network/protocols/httpwsProtocol.js
- /home/kuzzle/ems-iot/node_modules/kuzzle/lib/core/network/entryPoint.js
- /home/kuzzle/ems-iot/node_modules/kuzzle/lib/kuzzle/kuzzle.js
- /home/kuzzle/ems-iot/node_modules/kuzzle/lib/kuzzle/index.js
- /home/kuzzle/ems-iot/node_modules/kuzzle/lib/core/backend/backend.js
- /home/kuzzle/ems-iot/node_modules/kuzzle/lib/core/backend/index.js
- /home/kuzzle/ems-iot/node_modules/kuzzle/index.js
- /home/kuzzle/ems-iot/app.ts
    at /home/kuzzle/ems-iot/node_modules/uWebSockets.js/uws.js:22:9
    at Object.<anonymous> (/home/kuzzle/ems-iot/node_modules/uWebSockets.js/uws.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/kuzzle/ems-iot/node_modules/kuzzle/lib/core/network/protocols/httpwsProtocol.js:28:13)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/kuzzle/ems-iot/node_modules/kuzzle/lib/core/network/entryPoint.js:34:24)
```

## Context (Environment)

Kuzzle version: 2.16.7
Node.js version: 17.3.0
SDK version: 7.7.6

**Comment by Aschen** [comment]
Hi  @bobeal 

Your first ENOSPC bug is because of a limit on your OS. You need to increase this limit, this Stackoverflow thread gives some answers: https://stackoverflow.com/questions/55763428/react-native-error-enospc-system-limit-for-number-of-file-watchers-reached

About the second bug, it's because Kuzzle does not support Node.js 17. Because of our Http/WebSocket library (uWS) not supporting Node.js after version 16 in the version we are using. We will officially support Node.js 18 when it will be released because in the same time we will need to drop the Node.js 12 support.

**Comment by bobeal** [comment]
Great, it works after applying those 2 changes. Thanks!
