### ISSUE TITLE
Collection created through `Backend.import.mappings` should not be allowed to contains uppercase

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle#2270]
## Expected Behavior

Trying to create a collection with uppercase char should not be allowed

## Current Behavior

```
app.import.mappings({
  iot: {
    "productItem": {
      "mappings": {
        "dynamic": "strict",
        "properties": {
          "name": {
            "type": "keyword"
          },
        }
      }
    }
  }
})
```

**Comment by ChillPC** [comment]
Already satisfied [here](https://github.com/kuzzleio/kuzzle/blob/bddc11b884ab4756187b3a3ea56b727e8a96eb5e/lib/service/storage/elasticsearch.js#L3290) .

The code provided throws :
```
kuzzle_1         | [X] Cannot start Kuzzle 2.17.4: The collection name "productItem" is invalid
kuzzle_1         | [BadRequestError: The collection name "productItem" is invalid
kuzzle_1         |       [...Kuzzle internal calls deleted...]
kuzzle_1         |        at ElasticSearch._assertValidIndexAndCollection (/var/app/node_modules/kuzzle/lib/service/storage/elasticsearch.js:2899:20)
kuzzle_1         |        at ElasticSearch.createCollection (/var/app/node_modules/kuzzle/lib/service/storage/elasticsearch.js:1252:10)
kuzzle_1         |        at ClientAdapter.createCollection (/var/app/node_modules/kuzzle/lib/core/storage/clientAdapter.js:113:25)
kuzzle_1         |        at ClientAdapter.loadMappings (/var/app/node_modules/kuzzle/lib/core/storage/clientAdapter.js:937:22)
kuzzle_1         |        at processTicksAndRejections (internal/process/task_queues.js:95:5)
kuzzle_1         |        at Kuzzle.ask (/var/app/node_modules/kuzzle/lib/kuzzle/event/kuzzleEventEmitter.js:192:22)
kuzzle_1         |        at Kuzzle.importMappings (/var/app/node_modules/kuzzle/lib/kuzzle/kuzzle.js:304:13)
kuzzle_1         |        at Kuzzle.loadInitialState (/var/app/node_modules/kuzzle/lib/kuzzle/kuzzle.js:401:17)
kuzzle_1         |        at Kuzzle.start (/var/app/node_modules/kuzzle/lib/kuzzle/kuzzle.js:166:13)
kuzzle_1         |        at Backend.start (/var/app/node_modules/kuzzle/lib/core/backend/backend.js:185:9)] {
kuzzle_1         |   status: 400,
kuzzle_1         |   code: 16842794,
kuzzle_1         |   id: 'services.storage.invalid_collection_name'
kuzzle_1         | }
```

**Comment by alexandrebouthinon** [comment]
As mentioned by @ChillPC, this is now handled. So let's close this issue
