### ISSUE TITLE
starting with 'docker-compose up' fails

### ISSUE THREAD

**Issue by jveres** [kuzzleio/kuzzle#247]
Hi! Starting with 'docker-compose up'  doesn't seem to work for me.
I see a `kuzzle_kuzzle_1 exited with code 0` green entry in the startup logs.
The main branch works fine.
Any idea what can be wrong?
Thanks.

**Comment by j33f** [comment]
Hi there :) sorry about the inconvenient...
Could you give us some more informations ?
- which branch is failing ?
- which platform do you use ?
- could you post the startup logs here ?

Thanks for reporting :)

**Comment by jveres** [comment]
Sorry, it's the develop branch, I'm using Ubuntu 14.04.
Will post the logs later here.
Thanks for the swift reply:)

**Comment by jveres** [comment]
```
Attaching to kuzzle_elasticsearch_1, kuzzle_redis_1, kuzzle_kuzzle_1
redis_1          | 1:C 23 Apr 19:31:45.396 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1          |                 _._
redis_1          |            _.-``__ ''-._
redis_1          |       _.-``    `.  `_.  ''-._           Redis 3.0.7 (00000000/0) 64 bit
redis_1          |   .-`` .-```.  ```\/    _.,_ ''-._
redis_1          |  (    '      ,       .-`  | `,    )     Running in standalone mode
redis_1          |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1          |  |    `-._   `._    /     _.-'    |     PID: 1
redis_1          |   `-._    `-._  `-./  _.-'    _.-'
redis_1          |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1          |  |    `-._`-._        _.-'_.-'    |           http://redis.io
redis_1          |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1          |  |`-._`-._    `-.__.-'    _.-'_.-'|
redis_1          |  |    `-._`-._        _.-'_.-'    |
redis_1          |   `-._    `-._`-.__.-'_.-'    _.-'
redis_1          |       `-._    `-.__.-'    _.-'
redis_1          |           `-._        _.-'
redis_1          |               `-.__.-'
redis_1          |
redis_1          | 1:M 23 Apr 19:31:45.403 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1          | 1:M 23 Apr 19:31:45.403 # Server started, Redis version 3.0.7
redis_1          | 1:M 23 Apr 19:31:45.403 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memo
y = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1          | 1:M 23 Apr 19:31:45.403 * The server is now ready to accept connections on port 6379
kuzzle_kuzzle_1 exited with code 0
elasticsearch_1  | [2016-04-23 19:31:48,103][INFO ][node                     ] [Mark Scarlotti] version[2.2.0], pid[8], build[8ff36d1/2016-01-27T13:32:39Z]
elasticsearch_1  | [2016-04-23 19:31:48,105][INFO ][node                     ] [Mark Scarlotti] initializing ...
elasticsearch_1  | [2016-04-23 19:31:49,643][INFO ][plugins                  ] [Mark Scarlotti] modules [lang-expression, lang-groovy], plugins [], sites []
elasticsearch_1  | [2016-04-23 19:31:49,722][INFO ][env                      ] [Mark Scarlotti] using [1] data paths, mounts [[/ (/dev/mapper/docker-254:0-1705114-659ff02cda9422c
c5379601b2acf93c8fb2e0052139ee7a5be6b597100420a5)]], net usable_space [9gb], net total_space [9.7gb], spins? [possibly], types [ext4]
elasticsearch_1  | [2016-04-23 19:31:49,722][INFO ][env                      ] [Mark Scarlotti] heap size [989.8mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2016-04-23 19:31:55,085][INFO ][node                     ] [Mark Scarlotti] initialized
elasticsearch_1  | [2016-04-23 19:31:55,085][INFO ][node                     ] [Mark Scarlotti] starting ...
elasticsearch_1  | [2016-04-23 19:31:55,422][INFO ][transport                ] [Mark Scarlotti] publish_address {172.17.0.2:9300}, bound_addresses {[::]:9300}
elasticsearch_1  | [2016-04-23 19:31:55,446][INFO ][discovery                ] [Mark Scarlotti] elasticsearch/6MtTiNbgQZy-8HLPe_z94Q
elasticsearch_1  | [2016-04-23 19:31:58,766][INFO ][cluster.service          ] [Mark Scarlotti] new_master {Mark Scarlotti}{6MtTiNbgQZy-8HLPe_z94Q}{172.17.0.2}{172.17.0.2:9300},
eason: zen-disco-join(elected_as_master, [0] joins received)
elasticsearch_1  | [2016-04-23 19:31:58,867][INFO ][http                     ] [Mark Scarlotti] publish_address {172.17.0.2:9200}, bound_addresses {[::]:9200}
elasticsearch_1  | [2016-04-23 19:31:58,868][INFO ][node                     ] [Mark Scarlotti] started
elasticsearch_1  | [2016-04-23 19:31:59,008][INFO ][gateway                  ] [Mark Scarlotti] recovered [0] indices into cluster_state
```

**Comment by jveres** [comment]
Just tried with 1.0.0-RC1, same result.

**Comment by j33f** [comment]
could you try with ```docker-compose -f docker-compose/debug.yml up``` ?

**Comment by jveres** [comment]
Using `docker-compose/debug.yml` I see an error:
```
kuzzle_1         | [PM2] Spawning PM2 daemon
kuzzle_1         | [PM2] PM2 Successfully daemonized
kuzzle_1         | [PM2][WARN] Applications KuzzleServer, KuzzleWorker not running, starting...
kuzzle_1         | [PM2] App [KuzzleServer] launched (1 instances)
kuzzle_1         | [PM2] App [KuzzleWorker] launched (1 instances)
kuzzle_1         | ┌──────────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────────────┬──────────┐
kuzzle_1         | │ App name     │ id │ mode │ pid │ status │ restart │ uptime │ memory      │ watching │
kuzzle_1         | ├──────────────┼────┼──────┼─────┼────────┼─────────┼────────┼─────────────┼──────────┤
kuzzle_1         | │ KuzzleServer │ 0  │ fork │ 106 │ online │ 0       │ 0s     │ 24.754 MB   │  enabled │
kuzzle_1         | │ KuzzleWorker │ 1  │ fork │ 112 │ online │ 0       │ 0s     │ 22.098 MB   │  enabled │
kuzzle_1         | └──────────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────────────┴──────────┘
kuzzle_1         |  Use `pm2 show <id|name>` to get more details about an app
kuzzle_1         | [PM2] Tailing last 20 lines for [all] processes
kuzzle_1         |
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/lib/God/ActionMethods.js:516:30
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:322:29
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:44:16
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/lib/God/ActionMethods.js:511:18
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:181:20
kuzzle_1         | PM2:     at replenish (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:319:21)
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:330:15
kuzzle_1         | PM2:     at Object.async.forEachLimit.async.eachLimit (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:220:35)
kuzzle_1         | PM2: 2016-04-24 08:03:29: Trace: [Error: Unknown signal: USR1]
kuzzle_1         | PM2:     at Object.God.logAndGenerateError (/usr/lib/node_modules/pm2/lib/God/Methods.js:50:15)
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/lib/God/ActionMethods.js:516:30
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:322:29
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:44:16
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/lib/God/ActionMethods.js:511:18
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:181:20
kuzzle_1         | PM2:     at replenish (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:319:21)
kuzzle_1         | PM2:     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:330:15
kuzzle_1         | PM2:     at Object.async.forEachLimit.async.eachLimit (/usr/lib/node_modules/pm2/node_modules/async/lib/async.js:220:35)
kuzzle_1         |
kuzzle_1         | KuzzleServer-0 (err): Debugger listening on port 7000
kuzzle_1         |
kuzzle_1         | KuzzleWorker-1 (err): Debugger listening on port 7001
```
Another difference is that it starts a rabbit container too.
The whole log is just too long to put it here.
Let me know if you need it anyway, I will make a gist then.

**Comment by j33f** [comment]
what are the last ~10 lines ?

**Comment by jveres** [comment]
```
kuzzle_1         | KuzzleServer-0  ████████████████████████████████████
kuzzle_1         | KuzzleServer-0  ██     KUZZLE SERVER STARTED      ██
kuzzle_1         | KuzzleServer-0  ██   ...WAITING FOR WORKERS...    ██
kuzzle_1         | KuzzleServer-0  ████████████████████████████████████
kuzzle_1         | KuzzleServer-0 info: [2016-04-24T14:17:40.107Z]: internalBroker:*: Internal broker server started
rabbit_1         | 
rabbit_1         | =INFO REPORT==== 24-Apr-2016::14:17:40 ===
rabbit_1         | accepting AMQP connection <0.304.0> (172.17.0.5:47332 -> 172.17.0.4:5672)
kuzzle_1         | KuzzleWorker-1 info: [2016-04-24T14:17:40.627Z]: internalBroker:*: Connected to Kuzzle server
kuzzle_1         | KuzzleServer-0          ████████████████████████████████████
kuzzle_1         | KuzzleServer-0          ██        WORKER CONNECTED        ██
kuzzle_1         | KuzzleServer-0          ██    ...PREPARING DATABASE...    ██
kuzzle_1         | KuzzleServer-0          ████████████████████████████████████
kuzzle_1         | KuzzleServer-0 info: [2016-04-24T14:17:40.667Z]: log:info: == Starting DB preparation...
kuzzle_1         | KuzzleServer-0          ████████████████████████████████████
kuzzle_1         | KuzzleServer-0          ██          KUZZLE READY          ██
kuzzle_1         | KuzzleServer-0          ████████████████████████████████████
kuzzle_1         | KuzzleServer-0 info: [2016-04-24T14:17:40.692Z]: log:info: == No default mappings file specified in env vars: continue.
kuzzle_1         | KuzzleServer-0 info: [2016-04-24T14:17:40.693Z]: log:info: == Reading default fixtures file /var/app/features/fixtures/empty.json...
kuzzle_1         | KuzzleServer-0 info: [2016-04-24T14:17:40.694Z]: log:info: == Reading default fixtures file /var/app/features/fixtures/empty.json done.
kuzzle_1         | KuzzleServer-0 info: [2016-04-24T14:17:40.695Z]: log:info: == Index creation process terminated.
kuzzle_1         | KuzzleServer-0 info: [2016-04-24T14:17:40.696Z]: log:info: == All mapping imports launched.
kuzzle_1         | KuzzleServer-0 info: [2016-04-24T14:17:40.697Z]: log:info: == All fixtures imports launched.
kuzzle_1         | KuzzleServer-0 info: [2016-04-24T14:17:40.700Z]: log:info: == DB preparation done.
kuzzle_1         | KuzzleServer-0 [ℹ] There is no administrator user yet. You can use the CLI or the back-office to create one.
kuzzle_1         | KuzzleServer-0 [ℹ] Entering no-administrator mode: everyone has administrator rights.
```

**Comment by j33f** [comment]
OK Here we can see that Kuzzle has successfully started. 

Could you now stop it then try the ```docker-compose up``` command again to see if Kuzzle starts correctly ?

You can use this docker-compose fille right now, we'll see tomorrow with the team what's going wrong with the docker image.

**Comment by jveres** [comment]
No, it does not.
Tail of the log `docker-compose up` produces:
```
redis_1          | 1:M 24 Apr 14:24:50.868 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1          | 1:M 24 Apr 14:24:50.868 # Server started, Redis version 3.0.7
redis_1          | 1:M 24 Apr 14:24:50.868 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1          | 1:M 24 Apr 14:24:50.868 * The server is now ready to accept connections on port 6379
elasticsearch_1  | [2016-04-24 14:24:53,549][INFO ][node                     ] [Atom Bob] version[2.2.0], pid[8], build[8ff36d1/2016-01-27T13:32:39Z]
elasticsearch_1  | [2016-04-24 14:24:53,552][INFO ][node                     ] [Atom Bob] initializing ...
kuzzle100rc1_kuzzle_1 exited with code 0
elasticsearch_1  | [2016-04-24 14:24:55,219][INFO ][plugins                  ] [Atom Bob] modules [lang-expression, lang-groovy], plugins [], sites []
elasticsearch_1  | [2016-04-24 14:24:55,422][INFO ][env                      ] [Atom Bob] using [1] data paths, mounts [[/ (/dev/mapper/docker-254:0-1705114-b9393d900f3168f50a788e221579483d4669584e2cf5453ea08d9ba24a0d07f6)]], net usable_space [9gb], net total_space [9.7gb], spins? [possibly], types [ext4]
elasticsearch_1  | [2016-04-24 14:24:55,422][INFO ][env                      ] [Atom Bob] heap size [989.8mb], compressed ordinary object pointers [true]
elasticsearch_1  | [2016-04-24 14:25:00,704][INFO ][node                     ] [Atom Bob] initialized
elasticsearch_1  | [2016-04-24 14:25:00,704][INFO ][node                     ] [Atom Bob] starting ...
elasticsearch_1  | [2016-04-24 14:25:01,044][INFO ][transport                ] [Atom Bob] publish_address {172.17.0.2:9300}, bound_addresses {[::]:9300}
elasticsearch_1  | [2016-04-24 14:25:01,075][INFO ][discovery                ] [Atom Bob] elasticsearch/9gpq0EDhTNeqmhGhKjrPhA
elasticsearch_1  | [2016-04-24 14:25:04,409][INFO ][cluster.service          ] [Atom Bob] new_master {Atom Bob}{9gpq0EDhTNeqmhGhKjrPhA}{172.17.0.2}{172.17.0.2:9300}, reason: zen-disco-join(elected_as_master, [0] joins received)
elasticsearch_1  | [2016-04-24 14:25:04,527][INFO ][http                     ] [Atom Bob] publish_address {172.17.0.2:9200}, bound_addresses {[::]:9200}
elasticsearch_1  | [2016-04-24 14:25:04,528][INFO ][node                     ] [Atom Bob] started
elasticsearch_1  | [2016-04-24 14:25:04,694][INFO ][gateway                  ] [Atom Bob] recovered [0] indices into cluster_state
```

**Comment by j33f** [comment]
OK I have an intuition of what is wrong... We'll see tomorrow what to do with the team. 

Right now you can safely use the debug.yml file or create your own based on it (to not start the Rabbit server for instance, if you do not need MQ protocols).
We'll let you know about the resolution of this problem.

Thank you very much for taking time to report this! We all appreciate it :)

**Comment by jveres** [comment]
No problem.
Thanks for your help!

**Comment by j33f** [comment]
You're welcome!

**Comment by AnthonySendra** [comment]
Hello there,

I think we have a problem with our Docker images.  
The Kuzzle image is built with https://github.com/kuzzleio/kuzzle/blob/develop/Dockerfile and this Image inherits from https://github.com/kuzzleio/kuzzle-containers/blob/alpine/base/Dockerfile

The script `/run.sh` is never started ;)

**Comment by AnthonySendra** [comment]
Should be better now.

Try:
```
# In the directory where your docker-compose.yml is
$ docker-compose pull
$ docker-compose up
```

I close this issue, let us know if you still have a problem.
Thanks for your contribution!

**Comment by jveres** [comment]
Yep, it works.
Thanks:)
