### ISSUE TITLE
Bad plugin config causes entire management to be stuck

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle#431]
I have broken the config of my passport-oauth plugin, since my config does not have a `clientID` field, which causes an error when the plugin is refreshed.
The problem is that I see this error causes all the plugin management operations to crash.

Steps to reproduce
- install the `kuzzle-plugin-auth-passport-oauth` from github or npm
- install the `passport-google-oauth20` in the kuzzle root directory (otherwise the plugin will not start)
- set a bad config (e.g. with no `clientID` field)
- try to perform any plugin management operation, you'll likely get the following error

```
Failed to execute CLI action: OAuth2Strategy requires a clientID option
```

**Comment by xbill82** [comment]
Reproducing this issue after #403 and now:

- Kuzzle crashes on start with the error
```
kuzzle_1 | KuzzleServer-0 error: 2016-10-26T10:24:47+00:00 [LOG:ERROR] OAuth2Strategy requires a clientID option
kuzzle_1 | KuzzleServer-0 TypeError: OAuth2Strategy requires a clientID option
kuzzle_1 | KuzzleServer-0     at Strategy.OAuth2Strategy (/var/app/node_modules/passport-google-oauth2/node_modules/passport-oauth2/lib/strategy.js:82:34)
kuzzle_1 | KuzzleServer-0     at new Strategy (/var/app/node_modules/passport-google-oauth2/lib/oauth2.js:48:18)
kuzzle_1 | KuzzleServer-0     at /var/app/node_modules/kuzzle-plugin-auth-passport-oauth/lib/passport/strategy.js:34:18
kuzzle_1 | KuzzleServer-0     at Array.forEach (native)
kuzzle_1 | KuzzleServer-0     at module.exports.config.init (/var/app/node_modules/kuzzle-plugin-auth-passport-oauth/lib/passport/strategy.js:18:41)
kuzzle_1 | KuzzleServer-0     at module.exports.init.isDummy [as init] (/var/app/node_modules/kuzzle-plugin-auth-passport-oauth/lib/index.js:33:16)
kuzzle_1 | KuzzleServer-0     at /var/app/lib/api/core/plugins/pluginsManager.js:84:23
kuzzle_1 | KuzzleServer-0     at replenish (/var/app/node_modules/async/dist/async.js:884:21)
kuzzle_1 | KuzzleServer-0     at iterateeCallback (/var/app/node_modules/async/dist/async.js:869:21)
kuzzle_1 | KuzzleServer-0     at /var/app/node_modules/async/dist/async.js:847:20
kuzzle_1 | KuzzleServer-0     at /var/app/lib/api/core/plugins/pluginsManager.js:106:9
kuzzle_1 | KuzzleServer-0     at replenish (/var/app/node_modules/async/dist/async.js:884:21)
kuzzle_1 | KuzzleServer-0     at iterateeCallback (/var/app/node_modules/async/dist/async.js:869:21)
kuzzle_1 | KuzzleServer-0     at /var/app/node_modules/async/dist/async.js:847:20
kuzzle_1 | KuzzleServer-0     at /var/app/lib/api/core/plugins/pluginsManager.js:106:9
kuzzle_1 | KuzzleServer-0     at replenish (/var/app/node_modules/async/dist/async.js:884:21)
```
- Every CLI `plugins` operation hangs forever (even `--list`).
