### ISSUE TITLE
The body can't be empty

### ISSUE THREAD

**Issue by killerwolf** [kuzzleio/kuzzle#48]
Hello,

I am trying kuzzle for a side project

Here is my docker-compose.yml file
```yml
kuzzle:
  image: kuzzleio/kuzzle
  ports:
    - "7512:7512"
  links:
    - elasticsearch
    - redis
redis:
  image: redis:3.0.2
elasticsearch:
  image: elasticsearch:1.5.2
```

The following command is OK
```
curl -XGET http://192.168.99.100:7512/api/
{"error":null,"result":"Hello from Kuzzle :)"}
```

whereas
```
curl -XPOST http://192.168.99.100:7512/api/mycollection -d '{"id": 12345, "title": "my title"}'
```

return 
````
{"error":"The body can't be empty","result":null}
````

Here is kuzzle container logs
````
kuzzle_1        | KuzzleServer-0 error: [2015-10-25T16:17:19.152Z]: log:error:  Error: The body can't be empty
kuzzle_1        |     at RequestObject.isValid (/var/app/lib/api/core/models/requestObject.js:131:21)
kuzzle_1        |     at WriteController.create (/var/app/lib/api/controllers/writeController.js:16:19)
kuzzle_1        |     at FunnelController.<anonymous> (/var/app/lib/api/controllers/funnelController.js:45:68)
kuzzle_1        |     at Promise_then_fulfilled (/var/app/node_modules/q/q.js:766:44)
kuzzle_1        |     at Promise_done_fulfilled (/var/app/node_modules/q/q.js:835:31)
kuzzle_1        |     at Fulfilled_dispatch [as dispatch] (/var/app/node_modules/q/q.js:1229:9)
kuzzle_1        |     at Promise_done_task (/var/app/node_modules/q/q.js:871:28)
kuzzle_1        |     at RawTask.call (/var/app/node_modules/q/node_modules/asap/asap.js:40:19)
kuzzle_1        |     at flush (/var/app/node_modules/q/node_modules/asap/raw.js:50:29)
kuzzle_1        |     at doNTCallback0 (node.js:408:9)
kuzzle_1        |     at process._tickDomainCallback (node.js:378:13)
kuzzle_1        | KuzzleServer-0 error: [2015-10-25T16:17:19.158Z]: log:error:  Error: The body can't be empty
kuzzle_1        |     at RequestObject.isValid (/var/app/lib/api/core/models/requestObject.js:131:21)
kuzzle_1        |     at WriteController.create (/var/app/lib/api/controllers/writeController.js:16:19)
kuzzle_1        |     at FunnelController.<anonymous> (/var/app/lib/api/controllers/funnelController.js:45:68)
kuzzle_1        |     at Promise_then_fulfilled (/var/app/node_modules/q/q.js:766:44)
kuzzle_1        |     at Promise_done_fulfilled (/var/app/node_modules/q/q.js:835:31)
kuzzle_1        |     at Fulfilled_dispatch [as dispatch] (/var/app/node_modules/q/q.js:1229:9)
kuzzle_1        |     at Promise_done_task (/var/app/node_modules/q/q.js:871:28)
kuzzle_1        |     at RawTask.call (/var/app/node_modules/q/node_modules/asap/asap.js:40:19)
kuzzle_1        |     at flush (/var/app/node_modules/q/node_modules/asap/raw.js:50:29)
kuzzle_1        |     at doNTCallback0 (node.js:408:9)
kuzzle_1        |     at process._tickDomainCallback (node.js:378:13)
````

**Comment by scottinet** [comment]
Hi killerwolf,

Since you're transmitting JSON data through cURL, you need to specify the content encoding using the ``-H`` option.

Here is what your command line should look like, and the corresponding Kuzzle's response:

```sh
$ curl -XPOST http://192.168.99.100:7512/api/mycollection -H 'Content-Type: application/json' -d '{"id": 12345, "title": "my title"}'
{"error":null,"result":{"_index":"mainindex","_type":"mycollection","_id":"AVCjZLTEmsySTKTfa795","_version":1,"created":true,"requestId":"a1561a20-7bc0-11e5-9970-77e3b29820f7","controller":"write","action":"create","collection":"mycollection","_source":{"id":12345,"title":"my title"}}}
$ 
```

**Comment by scottinet** [comment]
I found the error you received not explicit enough, so I submitted  #49  to fix that.
Kuzzle now checks the encoding content of a message and get back to the user with an explicit error if the content is not encoded as a JSON object.

For instance, Kuzzle now responds to your request like this:
```sh
{"error":"Invalid request content-type. Expected \"application/json\", got: \"application/x-www-form-urlencoded\"","result":null}
```
