### ISSUE TITLE
Kuzzle hangs a long time on startup

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle#600]
Starting Kuzzle with Docker got extremely long.
It kind of hangs during 10 minutes after the green message

```
kuzzle_1         | [ℹ] Starting Kuzzle server
```

probably installing all the npm packages (but something compute-intensive is going on since Docker is KO).
If I enter the container and type `ps`, I get

```bash
root@d0d688f27c90:/var/app# ps aux | grep npm
root       145  0.0  0.0   4336    88 ?        S    00:09   0:00 /bin/sh -c npm install kuzzle-plugin-logger@2.0.5
root       146  0.0  0.0   4336    88 ?        S    00:09   0:00 /bin/sh -c npm install kuzzle-plugin-auth-passport-local@3.0.2
root       147 10.2  3.5 1250968 72424 ?       Dl   00:09   0:05 npm                                                                       
root       148 11.4  4.3 1250768 89268 ?       Dl   00:09   0:05 npm                                                                                    
root       168  0.0  0.0  11128   136 ?        S+   00:10   0:00 grep npm
root@d0d688f27c90:/var/app# 
```

After that, it starts normally.
This  happens all the time, even if I don't delete the container volume.

I'm using the standard `kuzzle-docker-compose.yml` provided in the kuzzleio/kuzzle-build repo.

**Comment by xbill82** [comment]
Update: I managed to launch a kuzzle (left the machine hanging during the night!) and launched the plugin install command via the CLI from inside the container. The CLI command hangs, outputs little dots, and Kuzzle logs say

```
kuzzle_1         | info: 2016-12-24T06:42:55+00:00 [LOG:INFO] ███ kuzzle-plugins: Installing plugin from path /tmp/kuzzle-plugin-bookr/...
kuzzle_1         | Error: Unable to update lock within the stale threshold
kuzzle_1         |     at options.fs.utimes (/var/app/node_modules/proper-lockfile/index.js:108:66)
kuzzle_1         |     at FSReqWrap.oncomplete (fs.js:123:15)
kuzzle_1         | App [KuzzleServer] with id [0] and pid [125], exited with code [1] via signal [SIGINT]
proxy_1          | Connection with backend ::ffff:172.20.0.5 closed.
kuzzle_1         | Starting execution sequence in -fork mode- for app name:KuzzleServer id:0
kuzzle_1         | App name:KuzzleServer id:0 online
```

**Comment by scottinet** [comment]
Outdated since the plugin refactor.
