### ISSUE TITLE
Node-gyp fails building boost-geospatial

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle#601]
When I `npm i` I get

```
> boost-geospatial-index@1.0.2 install /Users/luca/Documents/Dev/kuzzle/node_modules/boost-geospatial-index
> node-gyp rebuild

  CXX(target) Release/obj.target/BoostSpatialIndex/src/shape.o
In file included from ../src/shape.cc:1:
In file included from ../src/shape.hpp:5:
In file included from ../include/boost/geometry.hpp:17:
In file included from ../include/boost/geometry/geometry.hpp:50:
In file included from ../include/boost/geometry/strategies/strategies.hpp:32:
In file included from ../include/boost/geometry/strategies/intersection_strategies.hpp:20:
In file included from ../include/boost/geometry/policies/relate/intersection_points.hpp:20:
In file included from ../include/boost/geometry/algorithms/detail/assign_indexed_point.hpp:21:
In file included from ../include/boost/geometry/algorithms/detail/assign_values.hpp:28:
In file included from ../include/boost/geometry/algorithms/append.hpp:30:
In file included from ../include/boost/geometry/algorithms/num_interior_rings.hpp:36:
In file included from ../include/boost/geometry/algorithms/detail/counting.hpp:30:
../include/boost/geometry/util/range.hpp:229:21: error: no member named 'move' in namespace 'std'
        return std::move(first, last, out);
               ~~~~~^
In file included from ../src/shape.cc:1:
In file included from ../src/shape.hpp:5:
In file included from ../include/boost/geometry.hpp:17:
In file included from ../include/boost/geometry/geometry.hpp:50:
In file included from ../include/boost/geometry/strategies/strategies.hpp:87:
In file included from ../include/boost/geometry/strategies/transform/matrix_transformers.hpp:40:
In file included from ../include/boost/numeric/ublas/vector.hpp:21:
In file included from ../include/boost/numeric/ublas/storage.hpp:25:
In file included from ../include/boost/numeric/ublas/exception.hpp:19:
In file included from ../include/boost/numeric/ublas/detail/config.hpp:299:
../include/boost/numeric/ublas/fwd.hpp:21:10: fatal error: 'array' file not found
#include <array>
         ^
2 errors generated.
make: *** [Release/obj.target/BoostSpatialIndex/src/shape.o] Error 1
```

**Comment by xbill82** [comment]
Probably caused by this issue: when launching Kuzzle manually (tag 1.0.0-RC8) via pm2 I get

```
1|kuzzle   | Error: Could not locate the bindings file. Tried:
1|kuzzle   |  → /Users/luca/Documents/Dev/kuzzle/node_modules/espresso-logic-minimizer/build/EspressoLogicMinimizer.node
1|kuzzle   |  → /Users/luca/Documents/Dev/kuzzle/node_modules/espresso-logic-minimizer/build/Debug/EspressoLogicMinimizer.node
1|kuzzle   |  → /Users/luca/Documents/Dev/kuzzle/node_modules/espresso-logic-minimizer/build/Release/EspressoLogicMinimizer.node
1|kuzzle   |  → /Users/luca/Documents/Dev/kuzzle/node_modules/espresso-logic-minimizer/out/Debug/EspressoLogicMinimizer.node
1|kuzzle   |  → /Users/luca/Documents/Dev/kuzzle/node_modules/espresso-logic-minimizer/Debug/EspressoLogicMinimizer.node
1|kuzzle   |  → /Users/luca/Documents/Dev/kuzzle/node_modules/espresso-logic-minimizer/out/Release/EspressoLogicMinimizer.node
1|kuzzle   |  → /Users/luca/Documents/Dev/kuzzle/node_modules/espresso-logic-minimizer/Release/EspressoLogicMinimizer.node
1|kuzzle   |  → /Users/luca/Documents/Dev/kuzzle/node_modules/espresso-logic-minimizer/build/default/EspressoLogicMinimizer.node
1|kuzzle   |  → /Users/luca/Documents/Dev/kuzzle/node_modules/espresso-logic-minimizer/compiled/6.1.0/darwin/x64/EspressoLogicMinimizer.node
1|kuzzle   |     at bindings (/Users/luca/Documents/Dev/kuzzle/node_modules/bindings/bindings.js:88:9)
1|kuzzle   |     at Object.<anonymous> (/Users/luca/Documents/Dev/kuzzle/node_modules/espresso-logic-minimizer/index.js:1:111)
1|kuzzle   |     at Module._compile (module.js:541:32)
1|kuzzle   |     at Object.Module._extensions..js (module.js:550:10)
1|kuzzle   |     at Module.load (module.js:456:32)
1|kuzzle   |     at tryModuleLoad (module.js:415:12)
1|kuzzle   |     at Function.Module._load (module.js:407:3)
1|kuzzle   |     at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
1|kuzzle   |     at Module.require (module.js:466:17)
1|kuzzle   |     at require (internal/module.js:20:19)
1|kuzzle   |     at Object.<anonymous> (/Users/luca/Documents/Dev/kuzzle/lib/api/dsl/transform/canonical.js:6:14)
1|kuzzle   |     at Module._compile (module.js:541:32)
1|kuzzle   |     at Object.Module._extensions..js (module.js:550:10)
1|kuzzle   |     at Module.load (module.js:456:32)
1|kuzzle   |     at tryModuleLoad (module.js:415:12)
1|kuzzle   |     at Function.Module._load (module.js:407:3)
PM2        | App [kuzzle] with id [1] and pid [22757], exited with code [1] via signal [SIGINT]
PM2        | Script /Users/luca/Documents/Dev/kuzzle/bin/kuzzle had too many unstable restarts (16). Stopped. "errored"
```

**Comment by xbill82** [comment]
Oh, wait but... These errors are huge. It basically lacks of std. This may be due to my Mac configuration.

**Comment by xbill82** [comment]
LULZ https://svn.boost.org/trac/boost/ticket/8092

**Comment by xbill82** [comment]
Ok, filing this issue in the kuzzleio/boost-geospatial-indes repo.

**Comment by scottinet** [comment]
Closing this issue in favor of https://github.com/kuzzleio/boost-geospatial-index/issues/1
