### ISSUE TITLE
problem creating index

### ISSUE THREAD

**Issue by MassimoCappellano** [kuzzleio/kuzzle#639]
Hi, I'm started with kuzzle from docker composer
and trying to create an index (I'm following this article https://medium.com/building-a-slack-clone-with-vue-js-and-kuzzle-io/building-a-slack-clone-with-vue-js-and-kuzzle-io-part-1-d0c56ef9e6cb#.bphvzagqi):

`curl -X PUT http://localhost:7511/api/1.0/klack`

I've received this response:

```
{
    "requestId": "78dca4de-aa3b-49ad-a287-dcc685038e79",
    "status": 400,
    "error": {
        "status": 400,
        "message": "document:createOrReplace must specify a body.",
        "stack": "Error\n    at BadRequestError.KuzzleError (/var/app/node_modules/kuzzle-common-objects/lib/errors/kuzzleError.js:17:19)\n    at new BadRequestError (/var/app/node_modules/kuzzle-common-objects/lib/errors/badRequestError.js:6:15)\n    at requestAssertHasBody (/var/app/lib/api/controllers/util/requestAssertions.js:10:13)\n    at DocumentController.documentCreateOrReplace [as createOrReplace] (/var/app/lib/api/controllers/documentController.js:102:5)\n    at kuzzle.pluginsManager.trigger.then.newRequest (/var/app/lib/api/controllers/funnelController.js:253:80)\n    at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/var/app/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/var/app/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/var/app/node_modules/bluebird/js/release/promise.js:691:18)\n    at Async._drainQueue (/var/app/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/app/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/app/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:637:20)\n    at tryOnImmediate (timers.js:610:5)\n    at processImmediate [as _immediateCallback] (timers.js:582:5)"
    },
    "controller": "document",
    "action": "createOrReplace",
    "collection": "1.0",
    "index": "api",
    "metadata": null,
    "result": null
}
```

on the server console:

```
error: 2017-01-25T12:52:14+00:00 [LOG:ERROR]  status=400, message=document:createOrReplace must specify a body., stack=Error
kuzzle_1         |     at BadRequestError.KuzzleError (/var/app/node_modules/kuzzle-common-objects/lib/errors/kuzzleError.js:17:19)
kuzzle_1         |     at new BadRequestError (/var/app/node_modules/kuzzle-common-objects/lib/errors/badRequestError.js:6:15)
kuzzle_1         |     at requestAssertHasBody (/var/app/lib/api/controllers/util/requestAssertions.js:10:13)
kuzzle_1         |     at DocumentController.documentCreateOrReplace [as createOrReplace] (/var/app/lib/api/controllers/documentController.js:102:5)
kuzzle_1         |     at kuzzle.pluginsManager.trigger.then.newRequest (/var/app/lib/api/controllers/funnelController.js:253:80)
kuzzle_1         |     at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:16:23)
kuzzle_1         |     at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:510:31)
kuzzle_1         |     at Promise._settlePromise (/var/app/node_modules/bluebird/js/release/promise.js:567:18)
kuzzle_1         |     at Promise._settlePromise0 (/var/app/node_modules/bluebird/js/release/promise.js:612:10)
kuzzle_1         |     at Promise._settlePromises (/var/app/node_modules/bluebird/js/release/promise.js:691:18)
kuzzle_1         |     at Async._drainQueue (/var/app/node_modules/bluebird/js/release/async.js:133:16)
kuzzle_1         |     at Async._drainQueues (/var/app/node_modules/bluebird/js/release/async.js:143:10)
kuzzle_1         |     at Immediate.Async.drainQueues (/var/app/node_modules/bluebird/js/release/async.js:17:14)
kuzzle_1         |     at runCallback (timers.js:637:20)
kuzzle_1         |     at tryOnImmediate (timers.js:610:5)
kuzzle_1         |     at processImmediate [as _immediateCallback] (timers.js:582:5)

```

The documentation says:
http://docs.kuzzle.io/api-reference/#create56

so the request seems correc

If I try in this way

`curl -X PUT http://localhost:7511/api`

```
{
    "requestId": "2fe4e06e-cc06-4779-821d-30ce8664202e",
    "status": 200,
    "error": null,
    "controller": "index",
    "action": "create",
    "collection": null,
    "index": "api",
    "metadata": null,
    "result": {
        "acknowledged": true,
        "shards_acknowledged": true
    }
}

```
is OK

then

`http://localhost:7511/api/1.0`

```
{
  "requestId": "11a55a1f-c8f7-42ff-9675-55bbda858304",
  "status": 200,
  "error": null,
  "controller": "collection",
  "action": "create",
  "collection": "1.0",
  "index": "api",
  "metadata": null,
  "result": {
    "acknowledged": true
  }
}

```

But even now:

`http://localhost:7511/api/1.0/klack`

the same error:

```
{
  "requestId": "20c1742c-18df-4e7f-892a-ebc1c1315c57",
  "status": 400,
  "error": {
    "status": 400,
    "message": "document:createOrReplace must specify a body.",
    "stack": "Error\n    at BadRequestError.KuzzleError (/var/app/node_modules/kuzzle-common-objects/lib/errors/kuzzleError.js:17:19)\n    at new BadRequestError (/var/app/node_modules/kuzzle-common-objects/lib/errors/badRequestError.js:6:15)\n    at requestAssertHasBody (/var/app/lib/api/controllers/util/requestAssertions.js:10:13)\n    at DocumentController.documentCreateOrReplace [as createOrReplace] (/var/app/lib/api/controllers/documentController.js:102:5)\n    at kuzzle.pluginsManager.trigger.then.newRequest (/var/app/lib/api/controllers/funnelController.js:253:80)\n    at tryCatcher (/var/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/app/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/var/app/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/var/app/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/var/app/node_modules/bluebird/js/release/promise.js:691:18)\n    at Async._drainQueue (/var/app/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/var/app/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/var/app/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:637:20)\n    at tryOnImmediate (timers.js:610:5)\n    at processImmediate [as _immediateCallback] (timers.js:582:5)"
  },
  "controller": "document",
  "action": "createOrReplace",
  "collection": "1.0",
  "index": "api",
  "metadata": null,
  "result": null
}
```

Thanks for your work
Massimo

**Comment by MassimoCappellano** [comment]
I started

**Comment by ballinette** [comment]
Hi.
The article on Medium is outdated: the URL patterns have been harmonized and simplified since...
You no longer have to add `api/1.0` within the request.

This should work:
```
curl -X PUT http://localhost:7511/klack
```

**Comment by MassimoCappellano** [comment]
Thanks Gilles, yes I've tried, so it's OK.
