### ISSUE TITLE
installing kuzzle on mac (following your instructions) results in timeout error

### ISSUE THREAD

**Issue by florianbepunkt** [kuzzleio/kuzzle#690]
I tried to install kuzzle on mac via

```
$ wget http://kuzzle.io/docker-compose.yml
$ docker-compose up
```

the kuzzle server starts, but accessing http://localhost:7512/ results in a timeout error

```
{
"status": 500,
"message": "Kuzzle was too long to respond. Discarded request:\n[object Object]",
"stack": "Error\n    at InternalError.KuzzleError (/var/app/node_modules/kuzzle-common-objects/lib/errors/kuzzleError.js:17:19)\n    at new InternalError (/var/app/node_modules/kuzzle-common-objects/lib/errors/internalError.js:6:15)\n    at Timeout.setTimeout (/var/app/lib/store/PendingRequest.js:26:14)\n    at ontimeout (timers.js:365:14)\n    at tryOnTimeout (timers.js:237:5)\n    at Timer.listOnTimeout (timers.js:207:5)"
}
```

are there any prerequisites on mac I'm missing or is this a bug?

**Comment by florianbepunkt** [comment]
okay, nevermind. forgot to set vm.max_map_count=262144 in /etc/sysctl.conf
