### ISSUE TITLE
Cannot read property _kuzzle_info of undefined

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#707]
When using the `document:search` route with the following document body:

```json
{
  "stored_fields": []
}
```

Kuzzle responds with the following internal error: 

```
 "Error: Cannot read property '_kuzzle_info' of undefined
    at ElasticSearch.elasticsearchFormatESError [as formatESError] (/var/app/lib/services/elasticsearch.js:948:23)
    at client.search.then.catch.error (/var/app/lib/services/elasticsearch.js:194:43)
    at tryCallOne (/var/app/node_modules/promise/lib/core.js:37:12) 
    at /var/app/node_modules/promise/lib/core.js:123:15
    at flush (/var/app/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"
```

**Comment by scottinet** [comment]
Also occurs while passing the following property in the search body: `"_source": false` (works fine with any other `_source` value)
