### ISSUE TITLE
Route _getConfig is broken

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle#712]
Hello,

The route _getConfig try to access to:
```
return kuzzle.internalEngine.get('plugins', id);
```

With the plugin cluster this route returns:

```json
{
  "requestId": "1ee7dbe1-9ab4-4711-b14c-1593ca27b538",
  "status": 404,
  "error": {
    "message": "Not found: plugins/kuzzle-plugin-cluster",
    "status": 404,
    "stack": "Error\n    at NotFoundError.KuzzleError (/opt/kuzzle/node_modules/kuzzle-common-objects/lib/errors/kuzzleError.js:17:19)\n    at new NotFoundError (/opt/kuzzle/node_modules/kuzzle-common-objects/lib/errors/notFoundError.js:6:15)\n    at handleError (/opt/kuzzle/lib/services/internalEngine/index.js:395:27)\n    at client.get.catch.error (/opt/kuzzle/lib/services/internalEngine/index.js:129:23)\n    at tryCallOne (/opt/kuzzle/node_modules/promise/lib/core.js:37:12)\n    at /opt/kuzzle/node_modules/promise/lib/core.js:123:15\n    at flush (/opt/kuzzle/node_modules/asap/raw.js:50:29)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)"
  },
  "controller": "server",
  "action": "getConfig",
  "collection": null,
  "index": null,
  "metadata": null,
  "result": null
}
```

**Comment by scottinet** [comment]
The problem does not come from the cluster plugin: the route is broken, plugin configurations are not stored in ES anymore.

I'm going to add a functional test on this route and then fix it.

**Comment by gandbox** [comment]
@AnthonySendra @scottinet Done ? QA ?

**Comment by scottinet** [comment]
Done.
