### ISSUE TITLE
Diagtools crash: ENAMETOOLONG

### ISSUE THREAD

**Issue by scottinet** [kuzzleio/kuzzle#901]
When a dump is triggered, the error message is used as the dump directory name.

A check should be performed against that name and its size should be limited, to avoid this:

```
 ERROR: unknown error while trying to create dump folder
 { Error: ENAMETOOLONG: name too long, mkdir '/var/app/dump/20170629-084630-handled-internalerror-an-error-occured-during-the-creation-of-user-foo44-es_rejected_execution_exception-rejected-execution-of-org-elasticsearch-transport-transportservice-7-21870f08-on-esthreadpoolexecutor-bulk-queue-capacity-200-org-elasticsearch-common-util-concurrent-esthreadpoolexecutor-663515b9-running-pool-size-4-active-threads-4-queued-tasks-200-completed-tasks-500-es_rejected_execution_exception-rejected-execution-of-org-elasticsearch-transport-transportservice-7-1e5ee045-on-esthreadpoolexecutor-bulk-queue-capacity-200-org-elasticsearch-common-util-concurrent-esthreadpoolexecutor-663515b9-running-pool-size-4-active-threads-4-queued-tasks-200-completed-tasks-500'
     at Error (native)
     at Object.fs.mkdirSync (fs.js:922:18)
     at Object.mkdirsSync (/var/app/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:31:9)
     at e (/var/app/lib/api/controllers/cli/dump.js:68:10)
     at Promise._execute (/var/app/node_modules/bluebird/js/release/debuggability.js:300:9)
     at Promise._resolveFromExecutor (/var/app/node_modules/bluebird/js/release/promise.js:483:18)
     at new Promise (/var/app/node_modules/bluebird/js/release/promise.js:79:10)
     at Object.dump (/var/app/lib/api/controllers/cli/dump.js:56:10)
     at Immediate.setImmediate (/var/app/lib/api/controllers/funnelController.js:277:47)
     at runCallback (timers.js:637:20)
     at tryOnImmediate (timers.js:610:5)
     at processImmediate [as _immediateCallback] (timers.js:582:5)
   errno: -36,
   code: 'ENAMETOOLONG',
   syscall: 'mkdir',
   path: '/var/app/dump/20170629-084630-handled-internalerror-an-error-occured-during-the-creation-of-user-foo44-es_rejected_execution_exception-rejected-execution-of-org-elasticsearch-transport-transportservice-7-21870f08-on-esthreadpoolexecutor-bulk-queue-capacity-200-org-elasticsearch-common-util-concurrent-esthreadpoolexecutor-663515b9-running-pool-size-4-active-threads-4-queued-tasks-200-completed-tasks-500-es_rejected_execution_exception-rejected-execution-of-org-elasticsearch-transport-transportservice-7-1e5ee045-on-esthreadpoolexecutor-bulk-queue-capacity-200-org-elasticsearch-common-util-concurrent-esthreadpoolexecutor-663515b9-running-pool-size-4-active-threads-4-queued-tasks-200-completed-tasks-500' }
```

**Comment by scottinet** [comment]
This issue has been resolved.
