### ISSUE TITLE
Garbage collector is blocking kuzzle services init on start

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/kuzzle#984]
```
kuzzle              | [ℹ] Starting Kuzzle server
kuzzle              | registering oauth functions
kuzzle              | function () { [native code] }
kuzzle              | 2017-10-25T10:59:19+00:00 [LOG:INFO] [GC] Deleted 0 documents on collection selections of index global
kuzzle              | 2017-10-25T10:59:19+00:00 [LOG:INFO] [GC] Deleted 0 documents on collection default_config of index global
[..]
... 10s deleting
[..]
kuzzle              | 2017-10-25T10:59:29+00:00 [LOG:INFO] [GC] Deleted 0 documents on collection default_labels of index global
kuzzle              | 2017-10-25T10:59:29+00:00 [LOG:ERROR] {}
kuzzle              | [x] [ERROR] TimeoutError: operation timed out
kuzzle              |     at afterTimeout (/var/app/node_modules/bluebird/js/release/timers.js:46:19)
kuzzle              |     at Timeout.timeoutTimeout [as _onTimeout] (/var/app/node_modules/bluebird/js/release/timers.js:76:13)
kuzzle              |     at ontimeout (timers.js:386:14)
kuzzle              |     at tryOnTimeout (timers.js:250:5)
kuzzle              |     at Timer.listOnTimeout (timers.js:214:5)
kuzzle              | App [KuzzleServer] with id [0] and pid [264], exited with code [1] via signal [SIGINT]
kuzzle              | Starting execution sequence in -fork mode- for app name:KuzzleServer id:0
kuzzle              | App name:KuzzleServer id:0 online
```

**Comment by benoitvidis** [comment]
Most likely solved by https://github.com/kuzzleio/kuzzle/pull/975.
Kept open till confirmed
